"""Tests for Florida state statute converter.

Tests the FLConverter which fetches from leg.state.fl.us ("Online Sunshine")
and converts to the internal Section model.
"""

from datetime import date
from unittest.mock import patch

import pytest

from axiom_corpus.converters.us_states.fl import (
    FL_TAX_CHAPTERS,
    FL_WELFARE_CHAPTERS,
    FLConverter,
    FLConverterError,
    download_fl_chapter,
    fetch_fl_section,
)
from axiom_corpus.models import Section

# Sample HTML from leg.state.fl.us for testing
SAMPLE_SECTION_HTML = """<!DOCTYPE html>
<html>
<head><title>FL Statutes 220.02</title></head>
<body>
<h1>Title XIV</h1>
<h2>TAXATION AND FINANCE</h2>
<h3>Chapter 220</h3>
<h4>INCOME TAX CODE</h4>
<div class="Statute">
<p><b>220.02 Legislative intent.</b>--</p>
<p>(1) It is the intent of the Legislature that the income tax imposed by this code upon corporations be administered in a manner consistent with the applicable provisions of the Internal Revenue Code.</p>
<p>(2) It is the further intent of the Legislature that taxable income of the taxpayer be measured according to the value added to the economy of this state by the conduct of business within this state.</p>
<p>(a) For purposes of this section, the term "value added" means the value of economic activity generated by the taxpayer in this state.</p>
<p>(b) The Legislature finds that the apportionment formula provided in this code properly measures such value.</p>
<p>History.--s. 1, ch. 71-984; s. 4, ch. 82-243.</p>
</div>
</body>
</html>
"""

SAMPLE_CHAPTER_INDEX_HTML = """<!DOCTYPE html>
<html>
<head><title>Chapter 220 Index</title></head>
<body>
<h1>Chapter 220 - Income Tax Code</h1>
<div id="contents">
<ul>
<li><a href="Sections/0220.02.html">220.02 Legislative intent</a></li>
<li><a href="Sections/0220.03.html">220.03 Definitions</a></li>
<li><a href="Sections/0220.11.html">220.11 Tax imposed</a></li>
<li><a href="Sections/0220.12.html">220.12 Apportionment</a></li>
</ul>
</div>
</body>
</html>
"""


class TestFLChaptersRegistry:
    """Test Florida chapter registries."""

    def test_chapter_220_in_tax_chapters(self):
        """Chapter 220 (Income Tax) is in tax chapters."""
        assert 220 in FL_TAX_CHAPTERS
        assert "Income Tax" in FL_TAX_CHAPTERS[220]

    def test_chapter_212_in_tax_chapters(self):
        """Chapter 212 (Sales Tax) is in tax chapters."""
        assert 212 in FL_TAX_CHAPTERS
        assert "Sales" in FL_TAX_CHAPTERS[212]

    def test_chapter_409_in_welfare_chapters(self):
        """Chapter 409 (Social and Economic Assistance) is in welfare chapters."""
        assert 409 in FL_WELFARE_CHAPTERS
        assert "Social" in FL_WELFARE_CHAPTERS[409]

    def test_tax_chapters_range(self):
        """Tax chapters are in the expected range 192-220."""
        for chapter in FL_TAX_CHAPTERS:
            assert 192 <= chapter <= 220


class TestFLConverter:
    """Test FLConverter class."""

    def test_init_default(self):
        """Converter initializes with default settings."""
        converter = FLConverter()
        assert converter.rate_limit_delay == 0.5
        assert converter.year == date.today().year

    def test_init_custom_rate_limit(self):
        """Converter accepts custom rate limit."""
        converter = FLConverter(rate_limit_delay=1.0)
        assert converter.rate_limit_delay == 1.0

    def test_init_custom_year(self):
        """Converter accepts custom year."""
        converter = FLConverter(year=2024)
        assert converter.year == 2024

    def test_get_url_range_200s(self):
        """URL range calculation for chapters 200-299."""
        converter = FLConverter()
        assert converter._get_url_range(220) == "0200-0299"
        assert converter._get_url_range(212) == "0200-0299"

    def test_get_url_range_400s(self):
        """URL range calculation for chapters 400-499."""
        converter = FLConverter()
        assert converter._get_url_range(409) == "0400-0499"
        assert converter._get_url_range(430) == "0400-0499"

    def test_get_url_range_100s(self):
        """URL range calculation for chapters 100-199."""
        converter = FLConverter()
        assert converter._get_url_range(192) == "0100-0199"

    def test_build_section_url(self):
        """Build correct URL for section fetch."""
        converter = FLConverter()
        url = converter._build_section_url("220.02")
        assert "leg.state.fl.us/statutes" in url
        assert "0200-0299" in url
        assert "0220" in url
        assert "Sections/0220.02.html" in url

    def test_build_chapter_contents_url(self):
        """Build correct URL for chapter contents."""
        converter = FLConverter()
        url = converter._build_chapter_contents_url(220)
        assert "0220ContentsIndex.html" in url

    def test_context_manager(self):
        """Converter works as context manager."""
        with FLConverter() as converter:
            assert converter is not None
        # Client should be closed
        assert converter._client is None


class TestFLConverterParsing:
    """Test FLConverter HTML parsing."""

    def test_parse_section_html(self):
        """Parse section HTML into ParsedFLSection."""
        converter = FLConverter()
        parsed = converter._parse_section_html(SAMPLE_SECTION_HTML, "220.02", "https://example.com")

        assert parsed.section_number == "220.02"
        assert parsed.section_title == "Legislative intent"
        assert parsed.chapter_number == 220
        assert parsed.chapter_title == "Income Tax Code"
        assert parsed.title_roman == "XIV"
        assert parsed.title_name == "Taxation and Finance"
        assert "Internal Revenue Code" in parsed.text
        assert parsed.source_url == "https://example.com"

    def test_parse_subsections(self):
        """Parse subsections from section HTML."""
        converter = FLConverter()
        parsed = converter._parse_section_html(SAMPLE_SECTION_HTML, "220.02", "https://example.com")

        # Should have subsections (1) and (2)
        assert len(parsed.subsections) >= 2
        assert any(s.identifier == "1" for s in parsed.subsections)
        assert any(s.identifier == "2" for s in parsed.subsections)

    def test_parse_nested_subsections(self):
        """Parse nested subsections (a), (b) under (2)."""
        converter = FLConverter()
        parsed = converter._parse_section_html(SAMPLE_SECTION_HTML, "220.02", "https://example.com")

        # Find subsection (2)
        sub_2 = next((s for s in parsed.subsections if s.identifier == "2"), None)
        assert sub_2 is not None
        # Should have children (a) and (b)
        assert len(sub_2.children) >= 2
        assert any(c.identifier == "a" for c in sub_2.children)
        assert any(c.identifier == "b" for c in sub_2.children)

    def test_parse_history(self):
        """Parse history note from section HTML."""
        converter = FLConverter()
        parsed = converter._parse_section_html(SAMPLE_SECTION_HTML, "220.02", "https://example.com")

        assert parsed.history is not None
        assert "ch. 71-984" in parsed.history

    def test_to_section_model(self):
        """Convert ParsedFLSection to Section model."""
        converter = FLConverter()
        parsed = converter._parse_section_html(SAMPLE_SECTION_HTML, "220.02", "https://example.com")
        section = converter._to_section(parsed)

        assert isinstance(section, Section)
        assert section.citation.section == "FL-220.02"
        assert section.citation.title == 0  # State law indicator
        assert section.section_title == "Legislative intent"
        assert "Florida Statutes" in section.title_name
        assert section.uslm_id == "fl/220/220.02"
        assert section.source_url == "https://example.com"


class TestFLConverterFetching:
    """Test FLConverter HTTP fetching with mocks."""

    @patch.object(FLConverter, "_get")
    def test_fetch_section(self, mock_get):
        """Fetch and parse a single section."""
        mock_get.return_value = SAMPLE_SECTION_HTML

        converter = FLConverter()
        section = converter.fetch_section("220.02")

        assert section is not None
        assert isinstance(section, Section)
        assert section.citation.section == "FL-220.02"
        assert "Legislative intent" in section.section_title

    @patch.object(FLConverter, "_get")
    def test_fetch_section_not_found(self, mock_get):
        """Handle section not found error."""
        mock_get.return_value = "<html><body>Section cannot be found</body></html>"

        converter = FLConverter()
        with pytest.raises(FLConverterError) as exc_info:
            converter.fetch_section("999.99")

        assert "not found" in str(exc_info.value).lower()

    @patch.object(FLConverter, "_get")
    def test_get_chapter_section_numbers(self, mock_get):
        """Get list of section numbers from chapter index."""
        mock_get.return_value = SAMPLE_CHAPTER_INDEX_HTML

        converter = FLConverter()
        sections = converter.get_chapter_section_numbers(220)

        assert len(sections) == 4
        assert "220.02" in sections
        assert "220.03" in sections
        assert "220.11" in sections

    @patch.object(FLConverter, "_get")
    def test_iter_chapter(self, mock_get):
        """Iterate over sections in a chapter."""
        # First call returns index, subsequent calls return section HTML
        mock_get.side_effect = [
            SAMPLE_CHAPTER_INDEX_HTML,
            SAMPLE_SECTION_HTML,
            SAMPLE_SECTION_HTML,
            SAMPLE_SECTION_HTML,
            SAMPLE_SECTION_HTML,
        ]

        converter = FLConverter()
        sections = list(converter.iter_chapter(220))

        assert len(sections) == 4
        assert all(isinstance(s, Section) for s in sections)


class TestConvenienceFunctions:
    """Test module-level convenience functions."""

    @patch.object(FLConverter, "_get")
    def test_fetch_fl_section(self, mock_get):
        """Test fetch_fl_section function."""
        mock_get.return_value = SAMPLE_SECTION_HTML

        section = fetch_fl_section("220.02")

        assert section is not None
        assert section.citation.section == "FL-220.02"

    @patch.object(FLConverter, "_get")
    def test_download_fl_chapter(self, mock_get):
        """Test download_fl_chapter function."""
        mock_get.side_effect = [
            SAMPLE_CHAPTER_INDEX_HTML,
            SAMPLE_SECTION_HTML,
            SAMPLE_SECTION_HTML,
            SAMPLE_SECTION_HTML,
            SAMPLE_SECTION_HTML,
        ]

        sections = download_fl_chapter(220)

        assert len(sections) == 4
        assert all(isinstance(s, Section) for s in sections)


class TestFLConverterIntegration:
    """Integration tests that hit real leg.state.fl.us (marked slow)."""

    @pytest.mark.slow
    @pytest.mark.integration
    def test_fetch_income_tax_section(self):
        """Fetch Florida Income Tax section 220.02."""
        converter = FLConverter()
        section = converter.fetch_section("220.02")

        assert section is not None
        assert section.citation.section == "FL-220.02"
        assert "legislative intent" in section.section_title.lower()
        assert "income" in section.text.lower()

    @pytest.mark.slow
    @pytest.mark.integration
    def test_fetch_sales_tax_section(self):
        """Fetch Florida Sales Tax section 212.05."""
        converter = FLConverter()
        section = converter.fetch_section("212.05")

        assert section is not None
        assert section.citation.section == "FL-212.05"
        assert "sales" in section.text.lower() or "tax" in section.text.lower()

    @pytest.mark.slow
    @pytest.mark.integration
    def test_get_chapter_220_sections(self):
        """Get list of sections in Chapter 220."""
        converter = FLConverter()
        sections = converter.get_chapter_section_numbers(220)

        assert len(sections) > 0
        assert all(s.startswith("220.") for s in sections)
        assert "220.02" in sections  # Legislative intent

    @pytest.mark.slow
    @pytest.mark.integration
    def test_fetch_welfare_section(self):
        """Fetch Florida welfare section 409.2554."""
        converter = FLConverter()
        try:
            section = converter.fetch_section("409.2554")
            assert section.citation.section == "FL-409.2554"
        except FLConverterError:
            # Section may not exist, which is acceptable
            pytest.skip("Section 409.2554 not found")
