-- Empty Axiom-owned encoding tables used by the Encoder run history UI.
--
-- We intentionally do not migrate old validation/session rows here; this is a
-- clean RuleSpec-era surface. New runs can write to these tables going forward.

CREATE SCHEMA IF NOT EXISTS encodings;
CREATE SCHEMA IF NOT EXISTS app;
GRANT USAGE ON SCHEMA encodings TO postgres, service_role, anon, authenticated;

CREATE TABLE IF NOT EXISTS encodings.encoding_runs (
  id                     text PRIMARY KEY,
  "timestamp"            timestamptz NOT NULL DEFAULT now(),
  citation               text NOT NULL,
  iterations             jsonb NOT NULL DEFAULT '[]'::jsonb,
  scores                 jsonb NOT NULL DEFAULT '{}'::jsonb,
  final_scores           jsonb,
  has_issues             boolean,
  note                   text,
  total_duration_ms      integer,
  agent_type             text,
  agent_model            text,
  data_source            text NOT NULL DEFAULT 'unknown',
  session_id             text,
  file_path              text,
  rulespec_content       text,
  encoder_version        text,
  created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS encodings.agent_transcripts (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id             text NOT NULL,
  agent_id               text,
  tool_use_id            text NOT NULL,
  subagent_type          text NOT NULL,
  prompt                 text,
  description            text,
  response_summary       text,
  transcript             jsonb,
  orchestrator_thinking  text,
  message_count          integer NOT NULL DEFAULT 0,
  created_at             timestamptz NOT NULL DEFAULT now(),
  uploaded_at            timestamptz
);

CREATE TABLE IF NOT EXISTS encodings.sdk_sessions (
  id                     text PRIMARY KEY,
  started_at             timestamptz NOT NULL DEFAULT now(),
  ended_at               timestamptz,
  model                  text,
  cwd                    text,
  event_count            integer NOT NULL DEFAULT 0,
  input_tokens           bigint NOT NULL DEFAULT 0,
  output_tokens          bigint NOT NULL DEFAULT 0,
  cache_read_tokens      bigint NOT NULL DEFAULT 0,
  estimated_cost_usd     numeric,
  encoder_version        text,
  created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS encodings.sdk_session_events (
  id                     text PRIMARY KEY,
  session_id             text NOT NULL REFERENCES encodings.sdk_sessions(id) ON DELETE CASCADE,
  sequence               integer NOT NULL,
  "timestamp"            timestamptz NOT NULL DEFAULT now(),
  event_type             text NOT NULL,
  tool_name              text,
  content                text,
  metadata               jsonb,
  created_at             timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_encoding_runs_timestamp
  ON encodings.encoding_runs ("timestamp" DESC);
CREATE INDEX IF NOT EXISTS idx_encoding_runs_file_path
  ON encodings.encoding_runs (file_path)
  WHERE file_path IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_agent_transcripts_session
  ON encodings.agent_transcripts (session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sdk_sessions_started_at
  ON encodings.sdk_sessions (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sdk_session_events_session_sequence
  ON encodings.sdk_session_events (session_id, sequence);

ALTER TABLE encodings.encoding_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE encodings.agent_transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE encodings.sdk_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE encodings.sdk_session_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS anon_read ON encodings.encoding_runs;
CREATE POLICY anon_read ON encodings.encoding_runs
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON encodings.encoding_runs;
CREATE POLICY authenticated_read ON encodings.encoding_runs
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS anon_read ON encodings.agent_transcripts;
CREATE POLICY anon_read ON encodings.agent_transcripts
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON encodings.agent_transcripts;
CREATE POLICY authenticated_read ON encodings.agent_transcripts
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS anon_read ON encodings.sdk_sessions;
CREATE POLICY anon_read ON encodings.sdk_sessions
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON encodings.sdk_sessions;
CREATE POLICY authenticated_read ON encodings.sdk_sessions
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS anon_read ON encodings.sdk_session_events;
CREATE POLICY anon_read ON encodings.sdk_session_events
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON encodings.sdk_session_events;
CREATE POLICY authenticated_read ON encodings.sdk_session_events
  FOR SELECT TO authenticated USING (true);

GRANT SELECT ON encodings.encoding_runs TO anon, authenticated;
GRANT SELECT ON encodings.agent_transcripts TO anon, authenticated;
GRANT SELECT ON encodings.sdk_sessions TO anon, authenticated;
GRANT SELECT ON encodings.sdk_session_events TO anon, authenticated;

GRANT ALL ON encodings.encoding_runs TO postgres, service_role;
GRANT ALL ON encodings.agent_transcripts TO postgres, service_role;
GRANT ALL ON encodings.sdk_sessions TO postgres, service_role;
GRANT ALL ON encodings.sdk_session_events TO postgres, service_role;

DO $$
BEGIN
  IF to_regclass('encodings.agent_transcripts_id_seq') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE encodings.agent_transcripts_id_seq TO postgres, service_role';
  END IF;
END $$;

CREATE OR REPLACE FUNCTION encodings.get_encoding_runs(
  limit_count int DEFAULT 100,
  offset_count int DEFAULT 0
)
RETURNS TABLE (
  id text,
  "timestamp" timestamptz,
  citation text,
  iterations jsonb,
  scores jsonb,
  has_issues boolean,
  note text,
  total_duration_ms integer,
  agent_type text,
  agent_model text,
  data_source text,
  session_id text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = encodings
AS $$
  SELECT
    encoding_runs.id,
    encoding_runs."timestamp",
    encoding_runs.citation,
    encoding_runs.iterations,
    COALESCE(encoding_runs.scores, encoding_runs.final_scores, '{}'::jsonb) AS scores,
    encoding_runs.has_issues,
    encoding_runs.note,
    encoding_runs.total_duration_ms,
    encoding_runs.agent_type,
    encoding_runs.agent_model,
    encoding_runs.data_source,
    encoding_runs.session_id
  FROM encodings.encoding_runs
  ORDER BY encoding_runs."timestamp" DESC
  LIMIT GREATEST(1, LEAST(limit_count, 500))
  OFFSET GREATEST(0, offset_count);
$$;

GRANT EXECUTE ON FUNCTION encodings.get_encoding_runs(int, int) TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
