-- INTENTIONALLY EMPTY — superseded by 20260513140000.
--
-- Original purpose: version-aware corpus.navigation_nodes (ADD COLUMN
-- version + RLS policy + view).
--
-- This migration failed to apply: the parent migration 20260513100000's
-- synchronous backfill on corpus.provisions hit the pooler's
-- statement_timeout, the transaction rolled back, but side effects on
-- corpus.navigation_nodes (RLS policy + dropped path index) leaked.
-- Anon queries against corpus.navigation_nodes then hit
-- statement_timeout because they had no usable index and an
-- unevaluable RLS predicate referencing a non-existent column.
--
-- 20260513140000 installs the version-aware design without the
-- synchronous backfill (NULL-fallback in the view + RLS), restoring app
-- function and leaving the door open for an incremental backfill done
-- outside the migration transaction.
SELECT 1 WHERE FALSE;
