-- Precomputed navigation index for `corpus.provisions`.
--
-- The browser app derives tree navigation by repeatedly querying
-- `corpus.provisions` with prefix `LIKE` lookups. As state corpora grow that
-- query path has produced intermittent statement-timeout errors. This table is
-- a derived parent/child serving index, regenerated by `axiom-corpus-ingest
-- build-navigation-index`. The legal source text remains in
-- `corpus.provisions`; rows here only exist to make tree navigation a simple
-- indexed parent_path lookup.

CREATE TABLE IF NOT EXISTS corpus.navigation_nodes (
  id                         text PRIMARY KEY,
  jurisdiction               text NOT NULL,
  doc_type                   text NOT NULL,
  path                       text NOT NULL,
  parent_path                text,
  segment                    text NOT NULL,
  label                      text NOT NULL,
  sort_key                   text NOT NULL,
  depth                      integer NOT NULL,
  provision_id               text,
  citation_path              text,
  has_children               boolean NOT NULL DEFAULT false,
  child_count                integer NOT NULL DEFAULT 0,
  has_rulespec               boolean NOT NULL DEFAULT false,
  encoded_descendant_count   integer NOT NULL DEFAULT 0,
  status                     text,
  created_at                 timestamptz NOT NULL DEFAULT now(),
  updated_at                 timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE corpus.navigation_nodes IS
  'Derived parent/child serving index for browsing corpus.provisions. '
  'Generated and maintained by axiom-corpus; corpus.provisions remains the source of truth for legal text.';

COMMENT ON COLUMN corpus.navigation_nodes.path IS
  'Stable hierarchical path that mirrors corpus.provisions.citation_path.';
COMMENT ON COLUMN corpus.navigation_nodes.parent_path IS
  'Parent node path. NULL for top-level navigation roots in the (jurisdiction, doc_type) scope.';
COMMENT ON COLUMN corpus.navigation_nodes.segment IS
  'Trailing path component relative to parent_path (or the full path for roots).';
COMMENT ON COLUMN corpus.navigation_nodes.sort_key IS
  'Natural-order sort key with zero-padded numeric runs so 2 < 10 in browser tree order.';
COMMENT ON COLUMN corpus.navigation_nodes.depth IS
  'Distance from the (jurisdiction, doc_type) root in the rebuilt tree (root is 0).';
COMMENT ON COLUMN corpus.navigation_nodes.encoded_descendant_count IS
  'Bottom-up count of descendants (and self) with has_rulespec=true so encoded-only browsing can be served from this table.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_navigation_nodes_path
  ON corpus.navigation_nodes (path);

CREATE INDEX IF NOT EXISTS idx_navigation_nodes_parent_sort
  ON corpus.navigation_nodes (parent_path, sort_key);

CREATE INDEX IF NOT EXISTS idx_navigation_nodes_scope_parent_sort
  ON corpus.navigation_nodes (jurisdiction, doc_type, parent_path, sort_key);

-- Encoded-only browsing: descendants under a parent with any RuleSpec coverage.
CREATE INDEX IF NOT EXISTS idx_navigation_nodes_encoded_only
  ON corpus.navigation_nodes (parent_path, sort_key)
  WHERE encoded_descendant_count > 0 OR has_rulespec;

CREATE INDEX IF NOT EXISTS idx_navigation_nodes_provision_id
  ON corpus.navigation_nodes (provision_id)
  WHERE provision_id IS NOT NULL;

ALTER TABLE corpus.navigation_nodes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS anon_read ON corpus.navigation_nodes;
CREATE POLICY anon_read ON corpus.navigation_nodes
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON corpus.navigation_nodes;
CREATE POLICY authenticated_read ON corpus.navigation_nodes
  FOR SELECT TO authenticated USING (true);

GRANT SELECT ON corpus.navigation_nodes TO anon, authenticated;
GRANT ALL ON corpus.navigation_nodes TO postgres, service_role;

NOTIFY pgrst, 'reload schema';
