-- INTENTIONALLY EMPTY — see 20260513140000_restore_navigation_nodes_policy.sql.
--
-- Original purpose: extend corpus.release_scopes filtering to include the
-- provision-row version label (join on jurisdiction × document_class ×
-- version, not just jurisdiction × document_class).
--
-- The original SQL of this migration UPDATEd corpus.provisions to backfill
-- the new version column for every row in single-active-version
-- jurisdictions. With ~5M rows that UPDATE consistently hit the pooler's
-- statement_timeout (SQLSTATE 57014). The transaction rolled back, but
-- intermediate state on corpus.navigation_nodes (RLS policy + dropped
-- index) was already committed via a separate path and left the app
-- timing out on every anon read.
--
-- 20260513140000 restores the working pre-version-aware state. The
-- version-aware design needs a re-do that:
--   1. Adds the version column in its own transaction
--   2. Backfills in chunks (e.g., 10k rows per UPDATE) outside the
--      pooler statement_timeout window
--   3. Installs the version-filtered views and policies only after the
--      backfill completes
--
-- Issue: filed to track the re-do.
SELECT 1 WHERE FALSE;
