-- Cleanly rename encoder logs from the lab schema to telemetry.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.schemata WHERE schema_name = 'lab'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.schemata WHERE schema_name = 'telemetry'
  ) THEN
    ALTER SCHEMA lab RENAME TO telemetry;
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS telemetry;

DO $$
DECLARE
  table_name_var text;
BEGIN
  FOREACH table_name_var IN ARRAY ARRAY[
    'agent_transcripts',
    'sdk_sessions',
    'sdk_session_events'
  ]
  LOOP
    IF to_regclass(format('lab.%I', table_name_var)) IS NOT NULL THEN
      IF to_regclass(format('telemetry.%I', table_name_var)) IS NULL THEN
        EXECUTE format('ALTER TABLE lab.%I SET SCHEMA telemetry', table_name_var);
      ELSE
        EXECUTE format('DROP TABLE lab.%I CASCADE', table_name_var);
      END IF;
    END IF;
  END LOOP;

  IF to_regclass('lab.agent_transcripts_id_seq') IS NOT NULL THEN
    IF to_regclass('telemetry.agent_transcripts_id_seq') IS NULL THEN
      EXECUTE 'ALTER SEQUENCE lab.agent_transcripts_id_seq SET SCHEMA telemetry';
    ELSE
      EXECUTE 'DROP SEQUENCE lab.agent_transcripts_id_seq CASCADE';
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.schemata WHERE schema_name = 'lab'
  ) THEN
    EXECUTE 'DROP SCHEMA lab CASCADE';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS telemetry.agent_transcripts (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id             text NOT NULL,
  agent_id               text,
  tool_use_id            text NOT NULL,
  subagent_type          text NOT NULL,
  prompt                 text,
  description            text,
  response_summary       text,
  transcript             jsonb,
  orchestrator_thinking  text,
  message_count          integer NOT NULL DEFAULT 0,
  created_at             timestamptz NOT NULL DEFAULT now(),
  uploaded_at            timestamptz
);

CREATE TABLE IF NOT EXISTS telemetry.sdk_sessions (
  id                     text PRIMARY KEY,
  started_at             timestamptz NOT NULL DEFAULT now(),
  ended_at               timestamptz,
  model                  text,
  cwd                    text,
  event_count            integer NOT NULL DEFAULT 0,
  input_tokens           bigint NOT NULL DEFAULT 0,
  output_tokens          bigint NOT NULL DEFAULT 0,
  cache_read_tokens      bigint NOT NULL DEFAULT 0,
  estimated_cost_usd     numeric,
  encoder_version        text,
  created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS telemetry.sdk_session_events (
  id                     text PRIMARY KEY,
  session_id             text NOT NULL REFERENCES telemetry.sdk_sessions(id) ON DELETE CASCADE,
  sequence               integer NOT NULL,
  "timestamp"            timestamptz NOT NULL DEFAULT now(),
  event_type             text NOT NULL,
  tool_name              text,
  content                text,
  metadata               jsonb,
  created_at             timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, sequence)
);

ALTER TABLE IF EXISTS telemetry.sdk_sessions
  ADD COLUMN IF NOT EXISTS encoder_version text;

CREATE INDEX IF NOT EXISTS idx_agent_transcripts_session
  ON telemetry.agent_transcripts (session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sdk_sessions_started_at
  ON telemetry.sdk_sessions (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sdk_session_events_session_sequence
  ON telemetry.sdk_session_events (session_id, sequence);

ALTER TABLE telemetry.agent_transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry.sdk_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry.sdk_session_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS anon_read ON telemetry.agent_transcripts;
CREATE POLICY anon_read ON telemetry.agent_transcripts
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON telemetry.agent_transcripts;
CREATE POLICY authenticated_read ON telemetry.agent_transcripts
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS anon_read ON telemetry.sdk_sessions;
CREATE POLICY anon_read ON telemetry.sdk_sessions
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON telemetry.sdk_sessions;
CREATE POLICY authenticated_read ON telemetry.sdk_sessions
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS anon_read ON telemetry.sdk_session_events;
CREATE POLICY anon_read ON telemetry.sdk_session_events
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS authenticated_read ON telemetry.sdk_session_events;
CREATE POLICY authenticated_read ON telemetry.sdk_session_events
  FOR SELECT TO authenticated USING (true);

GRANT USAGE ON SCHEMA telemetry TO postgres, service_role, anon, authenticated;
GRANT SELECT ON telemetry.agent_transcripts TO anon, authenticated;
GRANT SELECT ON telemetry.sdk_sessions TO anon, authenticated;
GRANT SELECT ON telemetry.sdk_session_events TO anon, authenticated;
GRANT ALL ON telemetry.agent_transcripts TO postgres, service_role;
GRANT ALL ON telemetry.sdk_sessions TO postgres, service_role;
GRANT ALL ON telemetry.sdk_session_events TO postgres, service_role;

DO $$
BEGIN
  IF to_regclass('telemetry.agent_transcripts_id_seq') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE telemetry.agent_transcripts_id_seq TO postgres, service_role';
  END IF;
END $$;

ALTER ROLE authenticator SET pgrst.db_schemas = 'public,graphql_public,corpus,encodings,telemetry,app';

NOTIFY pgrst, 'reload config';
NOTIFY pgrst, 'reload schema';
